grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin1234

  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 30s

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true