apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: edf
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://YOUR_RDS_ENDPOINT:5432/edf_db"
  DB_USERNAME: "edf_admin"
  DB_PASSWORD: "CHANGE_ME"

  JWT_SECRET: "CHANGE_ME"

  MAIL_USERNAME: "CHANGE_ME"
  MAIL_APP_PASSWORD: "CHANGE_ME"

  GOOGLE_CLIENT_ID: "CHANGE_ME"
  GOOGLE_CLIENT_SECRET: "CHANGE_ME"

  NAVER_CLIENT_ID: "CHANGE_ME"
  NAVER_CLIENT_SECRET: "CHANGE_ME"

  KAKAO_CLIENT_ID: "CHANGE_ME"
  KAKAO_CLIENT_SECRET: "CHANGE_ME"

  GOOGLE_API_KEY: "CHANGE_ME"
  GOOGLE_MAPS_ID: "CHANGE_ME"

  KAKAO_API_KEY: "CHANGE_ME"

  FIREBASE_SERVICE_ACCOUNT_PATH: "/app/firebase/firebase-service-account.json"